import pydot

graph = pydot.Dot('my_graph', graph_type='digraph')

A_node = pydot.Node('A')
B_node = pydot.Node('B')
C_node = pydot.Node('C')
D_node = pydot.Node('D')
E_node = pydot.Node('E')
F_node = pydot.Node('F')
G_node = pydot.Node('G')
H_node = pydot.Node('H')
I_node = pydot.Node('I')
J_node = pydot.Node('J')

graph.add_node(A_node)
graph.add_node(B_node)
graph.add_node(C_node)
graph.add_node(D_node)
graph.add_node(E_node)
graph.add_node(F_node)
graph.add_node(G_node)
graph.add_node(H_node)
graph.add_node(I_node)
graph.add_node(J_node)

First_edge = pydot.Edge('A', 'B')
Second_edge = pydot.Edge('A', 'C')
Third_edge = pydot.Edge('B', 'D')
Fourth_edge = pydot.Edge('B', 'E')
Fifth_edge = pydot.Edge('A', 'D')
Sixth_edge = pydot.Edge('A', 'F')
Seventh_edge = pydot.Edge('F', 'G')
Eighth_edge = pydot.Edge('G', 'I')
Ninth_edge = pydot.Edge('G', 'H')


graph.add_edge(First_edge)
graph.add_edge(Second_edge)
graph.add_edge(Third_edge)
graph.add_edge(Fourth_edge)
graph.add_edge(Fifth_edge)
graph.add_edge(Sixth_edge)
graph.add_edge(Seventh_edge)
graph.add_edge(Eighth_edge)
graph.add_edge(Ninth_edge)

graph.write_raw('BigSample.dot')